### ISSUE TITLE
能不能加个获取指定ipv4或者ipv6的接口啊

### ISSUE THREAD

**Issue by rentianyu** [ccbikai/ip-api#1]
如题，
比如,下边这种，一个是获取4一个是获取6的
https://v4.ident.me
https://v6.ident.me

**Comment by miantiao-me** [comment]
Vercel 只支持 V4

CF 支持V4/V6

CF 可以自己改解析，然后 Worker 配一下触发路由。

<https://cloudflare-ip-v4.html.zone/>

<https://cloudflare-ip-v6.html.zone/>

我测试了下是可以的

**Comment by rentianyu** [comment]
感谢，我去试下！

**Comment by acocchat** [comment]
大佬，可以说一下具体的步骤吗？小白不懂
